# Generated by Django 2.1.7 on 2020-03-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200306_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='reviewer',
        ),
    ]
